schema:
  headers:
    - campaign
    - benefit
    - campaignResult
  explode:
    - benefit
  inside_fields:
    campaign:
      - type
      - channel
      - product
    campaignResult:
      - accomplishedStatus
      - remainingStatus
      - errors
      - average